import type { Campaign, ScheduledPost, AnalyticsData, AudienceInsight, ContentSuggestion } from './types'

export const campaigns: Campaign[] = [
  {
    id: '1',
    name: 'Summer Product Launch',
    status: 'active',
    platforms: [
      { name: 'instagram', enabled: true, followers: 125000, posts: 45 },
      { name: 'facebook', enabled: true, followers: 89000, posts: 32 },
      { name: 'twitter', enabled: true, followers: 45000, posts: 78 },
    ],
    budget: 15000,
    spent: 8750,
    startDate: '2026-02-01',
    endDate: '2026-03-31',
    targetAudience: {
      ageRange: [25, 45],
      locations: ['United States', 'Canada', 'United Kingdom'],
      interests: ['Technology', 'Innovation', 'Lifestyle'],
      demographics: ['Professionals', 'Early Adopters'],
    },
    performance: {
      impressions: 2450000,
      reach: 1850000,
      engagement: 185000,
      clicks: 45000,
      conversions: 2250,
      ctr: 1.84,
      cpc: 0.19,
      roi: 245,
    },
  },
  {
    id: '2',
    name: 'Brand Awareness Q1',
    status: 'active',
    platforms: [
      { name: 'linkedin', enabled: true, followers: 35000, posts: 22 },
      { name: 'twitter', enabled: true, followers: 45000, posts: 65 },
    ],
    budget: 8000,
    spent: 5200,
    startDate: '2026-01-15',
    endDate: '2026-03-15',
    targetAudience: {
      ageRange: [30, 55],
      locations: ['United States'],
      interests: ['Business', 'Marketing', 'Leadership'],
      demographics: ['Executives', 'Decision Makers'],
    },
    performance: {
      impressions: 980000,
      reach: 720000,
      engagement: 68000,
      clicks: 18500,
      conversions: 890,
      ctr: 1.89,
      cpc: 0.28,
      roi: 178,
    },
  },
  {
    id: '3',
    name: 'Holiday Sale Campaign',
    status: 'completed',
    platforms: [
      { name: 'instagram', enabled: true, followers: 125000, posts: 52 },
      { name: 'facebook', enabled: true, followers: 89000, posts: 38 },
      { name: 'tiktok', enabled: true, followers: 78000, posts: 25 },
    ],
    budget: 25000,
    spent: 24800,
    startDate: '2025-11-15',
    endDate: '2025-12-31',
    targetAudience: {
      ageRange: [18, 45],
      locations: ['United States', 'Canada'],
      interests: ['Shopping', 'Deals', 'Fashion'],
      demographics: ['Consumers', 'Shoppers'],
    },
    performance: {
      impressions: 5200000,
      reach: 3800000,
      engagement: 420000,
      clicks: 125000,
      conversions: 8500,
      ctr: 2.4,
      cpc: 0.2,
      roi: 380,
    },
  },
  {
    id: '4',
    name: 'Influencer Partnership',
    status: 'paused',
    platforms: [
      { name: 'instagram', enabled: true, followers: 125000, posts: 12 },
      { name: 'youtube', enabled: true, followers: 52000, posts: 4 },
    ],
    budget: 12000,
    spent: 4200,
    startDate: '2026-02-15',
    endDate: '2026-04-15',
    targetAudience: {
      ageRange: [18, 35],
      locations: ['United States'],
      interests: ['Fashion', 'Beauty', 'Lifestyle'],
      demographics: ['Gen Z', 'Millennials'],
    },
    performance: {
      impressions: 650000,
      reach: 480000,
      engagement: 52000,
      clicks: 12500,
      conversions: 680,
      ctr: 1.92,
      cpc: 0.34,
      roi: 145,
    },
  },
]

export const scheduledPosts: ScheduledPost[] = [
  {
    id: '1',
    campaignId: '1',
    content: 'Introducing our revolutionary new product line! Experience the future of innovation today. Early bird pricing ends soon.',
    platforms: ['instagram', 'facebook'],
    scheduledTime: '2026-03-11T10:00:00Z',
    status: 'scheduled',
    aiOptimized: true,
    predictedEngagement: 8.5,
  },
  {
    id: '2',
    campaignId: '1',
    content: 'Behind the scenes: Our team working on bringing you the best quality products. Every detail matters.',
    platforms: ['instagram', 'twitter'],
    scheduledTime: '2026-03-11T14:30:00Z',
    status: 'scheduled',
    aiOptimized: true,
    predictedEngagement: 6.2,
  },
  {
    id: '3',
    campaignId: '2',
    content: 'Leadership insights: 5 strategies that transformed our approach to customer success. Thread incoming.',
    platforms: ['linkedin', 'twitter'],
    scheduledTime: '2026-03-11T09:00:00Z',
    status: 'scheduled',
    aiOptimized: true,
    predictedEngagement: 4.8,
  },
  {
    id: '4',
    campaignId: '1',
    content: 'Customer spotlight: See how our solution helped increase productivity by 40%. Real results, real impact.',
    platforms: ['facebook', 'linkedin'],
    scheduledTime: '2026-03-12T11:00:00Z',
    status: 'scheduled',
    aiOptimized: false,
    predictedEngagement: 5.5,
  },
  {
    id: '5',
    campaignId: '1',
    content: 'Weekend vibes with our latest collection. Which style is your favorite? Comment below!',
    platforms: ['instagram', 'tiktok'],
    scheduledTime: '2026-03-13T16:00:00Z',
    status: 'scheduled',
    aiOptimized: true,
    predictedEngagement: 9.2,
  },
]

export const analyticsData: AnalyticsData[] = [
  { date: '2026-03-04', impressions: 125000, reach: 98000, engagement: 12500, clicks: 3200, conversions: 180 },
  { date: '2026-03-05', impressions: 142000, reach: 112000, engagement: 15800, clicks: 4100, conversions: 220 },
  { date: '2026-03-06', impressions: 138000, reach: 105000, engagement: 14200, clicks: 3800, conversions: 195 },
  { date: '2026-03-07', impressions: 165000, reach: 128000, engagement: 18500, clicks: 4800, conversions: 265 },
  { date: '2026-03-08', impressions: 178000, reach: 142000, engagement: 21200, clicks: 5400, conversions: 310 },
  { date: '2026-03-09', impressions: 195000, reach: 158000, engagement: 24500, clicks: 6100, conversions: 345 },
  { date: '2026-03-10', impressions: 210000, reach: 172000, engagement: 28000, clicks: 6800, conversions: 385 },
]

export const audienceInsights: AudienceInsight[] = [
  { category: 'Age 18-24', value: 22, change: 3.2, trend: 'up' },
  { category: 'Age 25-34', value: 38, change: 1.8, trend: 'up' },
  { category: 'Age 35-44', value: 25, change: -0.5, trend: 'stable' },
  { category: 'Age 45-54', value: 10, change: -1.2, trend: 'down' },
  { category: 'Age 55+', value: 5, change: -0.8, trend: 'down' },
]

export const contentSuggestions: ContentSuggestion[] = [
  {
    id: '1',
    type: 'carousel',
    content: 'Showcase your product features with an interactive carousel. Highlight 5 key benefits with stunning visuals.',
    hashtags: ['#ProductLaunch', '#Innovation', '#TechTrends', '#NewRelease'],
    predictedEngagement: 9.2,
    bestTime: '10:00 AM EST',
    platforms: ['instagram', 'linkedin'],
  },
  {
    id: '2',
    type: 'video',
    content: 'Create a 30-second testimonial video featuring customer success stories. Authentic voices drive trust.',
    hashtags: ['#CustomerSuccess', '#Testimonial', '#RealResults'],
    predictedEngagement: 8.7,
    bestTime: '2:00 PM EST',
    platforms: ['instagram', 'facebook', 'tiktok'],
  },
  {
    id: '3',
    type: 'story',
    content: 'Behind-the-scenes content performs 23% better. Show your team at work with interactive polls.',
    hashtags: ['#BTS', '#TeamWork', '#CompanyCulture'],
    predictedEngagement: 7.5,
    bestTime: '11:30 AM EST',
    platforms: ['instagram', 'facebook'],
  },
  {
    id: '4',
    type: 'reel',
    content: 'Quick tutorial showing your product in action. Keep it under 15 seconds for maximum retention.',
    hashtags: ['#HowTo', '#Tutorial', '#QuickTips'],
    predictedEngagement: 8.9,
    bestTime: '7:00 PM EST',
    platforms: ['instagram', 'tiktok'],
  },
]

export const platformStats = [
  { name: 'Instagram', followers: 125000, growth: 12.5, engagement: 4.8, color: 'chart-1' },
  { name: 'Facebook', followers: 89000, growth: 5.2, engagement: 2.3, color: 'chart-2' },
  { name: 'Twitter', followers: 45000, growth: 8.7, engagement: 3.1, color: 'chart-3' },
  { name: 'LinkedIn', followers: 35000, growth: 15.3, engagement: 5.2, color: 'chart-4' },
  { name: 'TikTok', followers: 78000, growth: 28.4, engagement: 8.5, color: 'chart-5' },
]

export const recentActivity = [
  { id: '1', action: 'Post published', platform: 'instagram', time: '2 mins ago', status: 'success' },
  { id: '2', action: 'Campaign optimized', platform: 'all', time: '15 mins ago', status: 'info' },
  { id: '3', action: 'New follower milestone', platform: 'tiktok', time: '1 hour ago', status: 'success' },
  { id: '4', action: 'Engagement spike detected', platform: 'facebook', time: '2 hours ago', status: 'info' },
  { id: '5', action: 'Budget alert', platform: 'linkedin', time: '3 hours ago', status: 'warning' },
]
